server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fast_food
    username: postgres
    password: 690
  application:
    name: AUTH-SERVICE
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
#            ddl-auto: create
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never
#      mode: always

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

jwt:
  secret-key: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
  expire:
    access_token: 604800000
    refresh_token: 1728000000

verification-code:
  expire-time: 10800000
  limit: 10000

twilio:
  account_sid: AC12f709df4c3da648649a6343133dfa85
  auth_token: 495e000c0e030a216fa823bb2404a28e
  phone_number: +19404129516

stripe:
  secret-key: sk_test_51JkAobLKO4a53BDZfp9GpkCGpBqM2an5RW9zDpbJcCbCpZCIcBf5wdD44Cnkq8KiBMkbqG7gy7DAw1DY07rS7tVb00g7927C5M



